In [1]:
import pandas as pd

df = pd.read_csv("D:\Project Sales_AnaLysis\Dataset\Sales Dataset.csv")

In [2]:
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

In [3]:
df.shape

(1194, 12)

In [5]:
df.columns

Index(['Order ID', 'Amount', 'Profit', 'Quantity', 'Category', 'Sub-Category',
       'PaymentMode', 'Order Date', 'CustomerName', 'State', 'City',
       'Year-Month'],
      dtype='object')

In [6]:
df.dtypes

Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
Order Date      object
CustomerName    object
State           object
City            object
Year-Month      object
dtype: object

In [7]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
Year-Month      0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.nunique()

Order ID        547
Amount          773
Profit          707
Quantity         20
Category          3
Sub-Category     12
PaymentMode       5
Order Date      648
CustomerName    802
State             6
City             18
Year-Month       61
dtype: int64

In [10]:
df["Category"].unique()

array(['Electronics', 'Office Supplies', 'Furniture'], dtype=object)

In [11]:
df["PaymentMode"].unique()

array(['UPI', 'Debit Card', 'EMI', 'Credit Card', 'COD'], dtype=object)

In [12]:
df["State"].unique()

array(['Florida', 'Illinois', 'New York', 'California', 'Texas', 'Ohio'],
      dtype=object)

In [13]:
df["Sub-Category"].unique()

array(['Electronic Games', 'Printers', 'Pens', 'Laptops', 'Tables',
       'Chairs', 'Markers', 'Sofas', 'Paper', 'Binders', 'Phones',
       'Bookcases'], dtype=object)

In [14]:
df[["Amount", "Profit", "Quantity"]].describe()

            Amount       Profit     Quantity
count  1194.000000  1194.000000  1194.000000
mean   5178.089615  1348.992462    10.674204
std    2804.921955  1117.992573     5.777102
min     508.000000    50.000000     1.000000
25%    2799.000000   410.000000     6.000000
50%    5152.000000  1014.000000    11.000000
75%    7626.000000  2035.000000    16.000000
max    9992.000000  4930.000000    20.000000

In [15]:
print("Amount <= 0:", (df["Amount"] <= 0).sum())
print("Profit <= 0:", (df["Profit"] <= 0).sum())
print("Quantity <= 0:", (df["Quantity"] <= 0).sum())

Amount <= 0: 0
Profit <= 0: 0
Quantity <= 0: 0

In [16]:
df[["Order Date", "Year-Month"]].head(10)

   Order Date Year-Month
0  2023-06-27    2023-06
1  2024-12-27    2024-12
2  2021-07-25    2021-07
3  2023-06-27    2023-06
4  2024-12-27    2024-12
5  2021-07-25    2021-07
6  2024-05-11    2024-05
7  2021-10-09    2021-10
8  2022-11-18    2022-11
9  2022-11-18    2022-11